### ISSUE TITLE
random crash with amqp connector

### ISSUE THREAD

**Issue by loafoe** [cloudfoundry-community/gautocloud#2]
Experiencing random crashes with amqp connector. Examining the `credentials of the amqp service entry in VCAP_SERVICES shows the following:

```json
...
     "hostname": "172.47.29.219",
     "hostnames": [
         "172.47.29.219"
     ],
...
```

Depending on the (random) order of parsing the amqp connector will crash in `decoder.affect()` if it inspects the `hostnames` array value first. 

The quick fix is to make the `Host` regex more specific so it does not match on `hostnames` (will send a PR), but looks like some additional checks should be added to the affect() method. Unfortunately did not have time to debug it further so far.

**Comment by ArthurHlt** [comment]
I've merged you PR, I will probably let it opens to remember that it should be able to use multiple hostnames
