### ISSUE TITLE
Support for DynamoDB

### ISSUE THREAD

**Issue by zdharmawan** [cloudfoundry-community/gautocloud#4]
Hi all,

There seems no support for DynamoDB yet? If I can probably I want to contribute here.

Regards,
Zul

**Comment by ArthurHlt** [comment]
Hi @zdharmawan, there is no support for DynameDB. You can totally contribute here, don't forget that there is no obligation to have this support directly inside this project. Connectors can be loaded from others imports.

**Comment by loafoe** [comment]
@zdharmawan @ArthurHlt I have implemented DynamoDB support for Philips HSDP CF environment. It's available at https://github.com/hsdp/gautocloud-connectors

Usage:

```go
import (
    "github.com/aws/aws-sdk-go/aws"
    "github.com/aws/aws-sdk-go/service/dynamodb"
    "github.com/cloudfoundry-community/gautocloud"
    "github.com/hsdp/gautocloud-connectors/hsdp"
)
```

```go
        db, err := gautocloud.GetFirst("hsdp:dynamodb-client")
        client, ok := db.(*hsdp.DynamoDBClient)
        if ok {
                fmt.Printf("Loaded DynamoDB client, table: %s\n", client.TableName)
                req := &dynamodb.DescribeTableInput{
                        TableName: aws.String(client.TableName),
                }
                result, err := client.DescribeTable(req)
                if err != nil {
                        fmt.Printf("%s", err)
                }
                table := result.Table
                fmt.Printf(table)
        } 
```
I'm finishing up some documentation but it should be usable already.

**Comment by ArthurHlt** [comment]
Hi @loafoe  feel free to add it to https://github.com/cloudfoundry-community/gautocloud/wiki/Connectors 

Thanks for your contribution

**Comment by ArthurHlt** [comment]
Finally i added them myself to the wiki ;)
