### ISSUE TITLE
How to get value from cups

### ISSUE THREAD

**Issue by yhjhoo** [cloudfoundry-community/gautocloud#5]
as the title, how to get value from cups in cloud foundry?

**Comment by loafoe** [comment]
@yhjhoo cups can be anything, so it'd be challenging to figure out the schema to match with. Do you have an example?

**Comment by ArthurHlt** [comment]
cups are treated as a normal service, we do use a lot of cups for configuration so we are using most of the time config connector, see it here: https://github.com/cloudfoundry-community/gautocloud/blob/master/docs/connectors.md#generic

**Comment by ArthurHlt** [comment]
feel free to close until you don't have more questions @yhjhoo
